version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Kishore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v09tudbxguf1"
s3_prefix = "Kishore"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
